### ISSUE TITLE
Make `RandomAccess` only work on already open storage

### ISSUE THREAD

**Issue by khernyo** [datrs/random-access-storage#7]
`RandomAccess` has methods corresponding to two separate states:
- `open()` should only be used in *unopened* state
- `read()`, `write()` and `del()` should only be used in *opened* state

To improve this, `RandomAccess` should be split into two structs, e.g.:
- `RandomAccessStorage` with an `fn open(self) -> Result<RandomAccess, Error>` method
- `RandomAccess` with the rest of the methods

This would improve stability and some of the methods might lose the mutable self-reference.

**Comment by yoshuawuyts** [comment]
I'm not opposed to this idea!

**Comment by yoshuawuyts** [comment]
Better even: I think this is a really good idea. Just dug into #9, and yeah we should definitely have an explicit open step. @khernyo is this something you'd like to work on?

**Comment by khernyo** [comment]
Sure, why not. It should be done by next week, and probably before this weekend.

**Comment by yoshuawuyts** [comment]
awesome :tada:

**Comment by khernyo** [comment]
I just found out that first the `read_to_writer()` methods need to be implemented, and I was thinking that we could instead have something like `fn reader() -> impl Read + Seek`. Then, `read_to_writer()` could be implemented using the reader and `std::io::copy()` if necessary. I'm gonna play around with it and see how it turns out.

**Comment by khernyo** [comment]
This is blocked on https://github.com/datrs/hypercore/pull/17

**Comment by yoshuawuyts** [comment]
@khernyo replied :sparkles:
